#!/usr/bin/env bash
set -eo pipefail; [[ -n "$PLUSHU_TRACE" ]] && set -x

# Check that dependencies are installed

if [[ ! -d "$PLUSHU_ROOT/plugins/git" ]]; then
  cat >&2 <<EOF
This plugin requires the plushu-git plugin.
You can install it with:

\$ plushu plugins:install git
EOF
fi

# Make the root directory for app files
mkdir -p "$PLUSHU_ROOT/apps"
if [[ "$EUID" == 0 ]]; then
  chown -R "$PLUSHU_USER" "$PLUSHU_ROOT/apps"
fi
