#!/usr/bin/env bash
set -eo pipefail; [[ $PLUSHU_TRACE ]] && set -x

# Check that dependencies are installed

if [[ ! -d "$PLUSHU_ROOT/plugins/git-hooking" ]]; then
  cat >&2 <<EOF
This plugin requires the plushu-git-hooking plugin.
You can install it with:

\$ plushu plugins:install git-hooking
EOF
fi

# Make the root directory for app files
mkdir -p "$PLUSHU_ROOT/apps"
if [[ $EUID == 0 ]]; then
  chown -R plushu "$PLUSHU_ROOT/apps"
fi
